### PR TITLE
Switch to cross-compilation for `linux_aarch64` and `linux_ppc64le`

### PR DESCRIPTION
**Pull request by bdice**
This PR switches to cross-compilation for `linux_aarch64` and `linux_ppc64le`.

See https://github.com/conda-forge/cuda-feedstock/issues/25

### CODE REVIEW

**Review by adibbley — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

Noticed that `linux_aarch64` failed. It appears this is due to `arm-variant` being `linux_aarch64` only

```
Could not solve for environment specs
The following package could not be installed
└─ arm-variant * sbsa does not exist (perhaps a typo or a missing channel).
```

It might be worth making `arm-variant` `noarch`. It need not be platform specific

Edit: Raising upstream issue ( https://github.com/conda-forge/arm-variant-feedstock/issues/4 )

**Comment by jakirkham** [comment]
With PR ( https://github.com/conda-forge/arm-variant-feedstock/pull/5 ) in, am restarting the failed CI job

**Comment by jakirkham** [comment]
This is now passing! 🎉

**Comment by jakirkham** [comment]
Thanks Bradley and Alex! 🙏

Merging as it sounds like we are happy to go forward based on our offline discussion earlier

Let's look at doing the rest after CUDA 12.4.1 is shipped: https://github.com/conda-forge/cuda-feedstock/issues/23

**Pull request merged**
